internal class TBFinances
{
    public decimal FinanceId { get; set; }
    public string FinanceType { get; set; }
    public string Code { get; set; }
    public decimal? ExpenseId { get; set; }
    public string ExpenseName { get; set; }
    public string Opdipd { get; set; }
    public decimal OrderId { get; set; }
    public DateTime? OrderDate { get; set; }
    public DateTime? OrderTime { get; set; }
    public decimal? OpdRightId { get; set; }
    public decimal? ServiceId { get; set; }
    public decimal? ClinicId { get; set; }
    public decimal PatientId { get; set; }
    public int RunHn { get; set; }
    public int YearHn { get; set; }
    public string Hn { get; set; }
    public decimal? AdmitId { get; set; }
    public decimal? RunAn { get; set; }
    public decimal? YearAn { get; set; }
    public string An { get; set; }
    public decimal? Age { get; set; }
    public string Gender { get; set; }
    public decimal? Pttype { get; set; }
    public decimal FromWork { get; set; }
    public decimal? ToWork { get; set; }
    public decimal Price { get; set; }
    public decimal Quantity { get; set; }
    public decimal Amount { get; set; }
    public decimal Claim { get; set; }
    public decimal Copay { get; set; }
    public decimal Discount { get; set; }
    public decimal Payment { get; set; }
    public decimal Reminburse { get; set; }
    public decimal? Cost { get; set; }
    public string Doctor { get; set; }
    public string Status { get; set; }
    public string UserStatused { get; set; }
    public DateTime? DateStatused { get; set; }
    public string DrugUsing { get; set; }
    public string DrugTiming { get; set; }
    public string DrugWarning { get; set; }
    public string DrugProperty { get; set; }
    public string DrugLabel { get; set; }
    public decimal? Dose { get; set; }
    public decimal? Duration { get; set; }
    public DateTime? StartDate { get; set; }
    public DateTime? EndDate { get; set; }
    public decimal? Formula { get; set; }
    public string Reason { get; set; }
    public string NedFlag { get; set; }
    public string FirstDoseFlag { get; set; }
    public string RushFlag { get; set; }
    public string AdrFlag { get; set; }
    public string ReadingFlag { get; set; }
    public string HmFlag { get; set; }
    public string GenFlag { get; set; }
    public string DiFlag { get; set; }
    public string DiComponent { get; set; }
    public string OrderRemark { get; set; }
    public decimal Billgroup { get; set; }
    public decimal Actgroup { get; set; }
    public decimal? Accgroup { get; set; }
    public string Cscd { get; set; }
    public string Nhso { get; set; }
    public string Sso { get; set; }
    public string SampleId { get; set; }
    public decimal? PackageId { get; set; }
    public string QueueNo { get; set; }
    public string QueueBranch { get; set; }
    public string UserCreated { get; set; }
    public DateTime? DateCreated { get; set; }
    public string UserModified { get; set; }
    public DateTime? DateModified { get; set; }
    public string UserAccepted { get; set; }
    public DateTime? DateAccepted { get; set; }
    public string UserPrepared { get; set; }
    public DateTime? DatePrepared { get; set; }
    public string UserChecked { get; set; }
    public DateTime? DateChecked { get; set; }
    public string UserDispensed { get; set; }
    public DateTime? DateDispensed { get; set; }
    public string UserPayabled { get; set; }
    public DateTime? DatePayabled { get; set; }
    public string UserAdr { get; set; }
    public DateTime? DateAdr { get; set; }
    public string AdrReason { get; set; }
    public decimal? AdmitRightId { get; set; }
    public string DummyFlag { get; set; }
    public string Route { get; set; }
    public string DosingInterval { get; set; }
    public decimal? RefillId { get; set; }
    public string DocRemark { get; set; }
    public string DocLabel1 { get; set; }
    public string DocLabel2 { get; set; }
    public string DocLabel3 { get; set; }
    public string DocLabel4 { get; set; }
    public decimal? Sachet { get; set; }
    public string DosingUnit { get; set; }
    public string DosingTime { get; set; }
    public decimal? AlternateDay { get; set; }
    public string OtherDosingInterval { get; set; }
    public string DrugAdmin { get; set; }
    public int AccessionNo { get; set; }
    public DateTime? PacsDttm { get; set; }
    public DateTime? StudyDttm { get; set; }
    public string DoctorDoneFlag { get; set; }
    public string RightId { get; set; }
    public string AlertType { get; set; }
    public string Generic { get; set; }
    public decimal? OrRecId { get; set; }
    public decimal? ReturnQty { get; set; }
    public decimal Receive { get; set; }
    public DateTime? DateReceived { get; set; }
    public string UserReceived { get; set; }
    public decimal? AppointId { get; set; }
    public decimal? DrugProfileId { get; set; }
    public decimal? CashNotReturn { get; set; }
    public decimal? CashReturn { get; set; }
    public decimal? Credit { get; set; }
    public string DoseText { get; set; }
    public string IpModified { get; set; }
    public decimal? Labnumber { get; set; }
    public decimal? MainFinanceid { get; set; }
    public DateTime? RobotDttm { get; set; }
    public string RobotStatus { get; set; }
    public decimal? RootClaim { get; set; }
    public decimal? RootCopay { get; set; }
    public decimal? RootPrice { get; set; }
    public decimal? RootQty { get; set; }
    public string Specimen { get; set; }
    public DateTime? SpecimenDate { get; set; }
    public string SpecimenUser { get; set; }
    public string WardDoneFlag { get; set; }
    public decimal? AcceptPlace { get; set; }
    public string GenErrorMessage { get; set; }
    public decimal? DailyNo { get; set; }
    public string DocDrugLabel { get; set; }
    public decimal? DocQty { get; set; }
    public decimal? OldQty { get; set; }
    public string GenErrorFlag { get; set; }
    public string BagSpecialDrug { get; set; }
    public string DocSignFlag { get; set; }
    public string Fptype { get; set; }
    public string InnovationDrug { get; set; }
    public string Liscode { get; set; }
    public string SampleFlag { get; set; }
    public decimal? DiId { get; set; }
    public decimal? PtAdrId { get; set; }
    public decimal? PtDgAdrId { get; set; }
    public decimal? SaftyId { get; set; }
    public string OrderType { get; set; }
    //public string ORDER_TYPE { get; set; }
    public string LockFlag { get; set; }
    public string NotTriggerFlag { get; set; }
    public decimal? DiscountId { get; set; }
    public DateTime? DoseStart { get; set; }
    public string Mapping1 { get; set; }
    public string Mapping2 { get; set; }
    public string Mapping3 { get; set; }
    public string Mapping4 { get; set; }
    public string Mapping5 { get; set; }
    public decimal? SplitNo { get; set; }
    public string Teeth { get; set; }
    public string DoctorNote { get; set; }
    public DateTime? DateEndDose { get; set; }
    public DateTime? DateStartDose { get; set; }
    public string NotResultFlag { get; set; }
    public string DoctorXray { get; set; }
    public decimal? PtCodeAdrId { get; set; }
    public decimal? SpecimenVol { get; set; }
    public string DfStatus { get; set; }
    public DateTime? CanPayDfDate { get; set; }
    public string Frequency { get; set; }
    public string PerTime { get; set; }
}