internal class TBMExpenses
{
    public decimal ExpenseId { get; set; }
    public string FinanceType { get; set; }
    public string Code { get; set; }
    public string Name { get; set; }
    public string EName { get; set; }
    public string Name2 { get; set; }
    public string Name3 { get; set; }
    public string Genericname { get; set; }
    public string Tradename { get; set; }
    public decimal? Billgroup { get; set; }
    public decimal? Actgroup { get; set; }
    public decimal? Accgroup { get; set; }
    public string Cscd { get; set; }
    public string Nhso { get; set; }
    public string Sso { get; set; }
    public string Erp { get; set; }
    public string Xcode { get; set; }
    public string Ncd24 { get; set; }
    public string Gpu { get; set; }
    public string Tmt { get; set; }
    public string Invest { get; set; }
    public string Loinc { get; set; }
    public string DosageForm { get; set; }
    public decimal? GoodsId { get; set; }
    public decimal? MinRate { get; set; }
    public decimal? MaxRate { get; set; }
    public decimal? IpdRate { get; set; }
    public decimal? CscdRate { get; set; }
    public decimal? DfRate { get; set; }
    public decimal? ShareRate { get; set; }
    public decimal? Cost { get; set; }
    public decimal? P4p { get; set; }
    public string Antibiotic { get; set; }
    public string EdType { get; set; }
    public string Pregnancy { get; set; }
    public string Productcat { get; set; }
    public string Specprep { get; set; }
    public string Ised { get; set; }
    public string Csrevrate { get; set; }
    public string Strength { get; set; }
    public string DueReport { get; set; }
    public string Content { get; set; }
    public string PopupText { get; set; }
    public string DoctorNote { get; set; }
    public string DrugNote { get; set; }
    public string UnitText { get; set; }
    public string PrepareUnit { get; set; }
    public string AdmixingUnit { get; set; }
    public decimal? Autostop { get; set; }
    public decimal? AdmixingExp { get; set; }
    public decimal? AdmixingVolume { get; set; }
    public decimal? MlVolume { get; set; }
    public string ReasonFlag { get; set; }
    public string FoodReactFlag { get; set; }
    public string OriginalFlag { get; set; }
    public string NotPrintFlag { get; set; }
    public string QtyPrintFlag { get; set; }
    public string FirstDoseFlag { get; set; }
    public string DoctorFlag { get; set; }
    public string ShareFlag { get; set; }
    public string IntimeFlag { get; set; }
    public string ResultFlag { get; set; }
    public string AutoMeaning { get; set; }
    public string LabMeaning { get; set; }
    public decimal? WaitingTime { get; set; }
    public string Proced { get; set; }
    public string Diag { get; set; }
    public DateTime? Dateeff { get; set; }
    public DateTime? Dateexp { get; set; }
    public string DrugUsing { get; set; }
    public string DrugTiming { get; set; }
    public string DrugWarning { get; set; }
    public string DrugProperty { get; set; }
    public string Mapping1 { get; set; }
    public string Mapping2 { get; set; }
    public string Mapping3 { get; set; }
    public string Mapping4 { get; set; }
    public string Mapping5 { get; set; }
    public decimal? Seq { get; set; }
    public string UserCreated { get; set; }
    public DateTime? DateCreated { get; set; }
    public string UserModified { get; set; }
    public DateTime? DateModified { get; set; }
    public string CancelFlag { get; set; }
    public string Prefix { get; set; }
    public string Labgroup { get; set; }
    public string Modality { get; set; }
    public string DummyFlag { get; set; }
    public string Route { get; set; }
    public string DosingInterval { get; set; }
    public string DrugLabel { get; set; }
    public string DrugSpecification { get; set; }
    public string Highalert { get; set; }
    public string Specimen { get; set; }
    public decimal? ToWork { get; set; }
    public string DosingUnit { get; set; }
    public string DosingTime { get; set; }
    public decimal? AlternateDay { get; set; }
    public string OtherDosingInterval { get; set; }
    public string DrugAdmin { get; set; }
    public decimal? ProfileLab { get; set; }
    public string Narcotic { get; set; }
    public string Danger { get; set; }
    public string AdmixingFlag { get; set; }
    public string ChemoFlag { get; set; }
    public decimal? Dose { get; set; }
    public string Keeping { get; set; }
    public decimal? DripRate { get; set; }
    public string DripUnit { get; set; }
    public string Container { get; set; }
    public string Solvent { get; set; }
    public decimal? WkFormulaId { get; set; }
    public string Manufacturer { get; set; }
    public string Vcctype { get; set; }
    public decimal? Vccday2 { get; set; }
    public decimal? Vccday3 { get; set; }
    public decimal? Vccday4 { get; set; }
    public decimal? Vccday5 { get; set; }
    public decimal? Vccday6 { get; set; }
    public decimal? Vccday7 { get; set; }
    public decimal? Vccday8 { get; set; }
    public decimal? Vccday9 { get; set; }
    public decimal? Vccday10 { get; set; }
    public decimal? Vccday11 { get; set; }
    public string AlienFlag { get; set; }
    public decimal? AlienIpdRate { get; set; }
    public decimal? AlienRate { get; set; }
    public string Breastfeeding { get; set; }
    public string CscdFlag { get; set; }
    public decimal? CscdIpdRate { get; set; }
    public string CutStockFlag { get; set; }
    public string DocPopupText { get; set; }
    public decimal? DrugConcentration { get; set; }
    public string DrugGender { get; set; }
    public string FoodDiDesc { get; set; }
    public string FoodDiFlag { get; set; }
    public string InsuranceFlag { get; set; }
    public decimal? InsuranceIpdRate { get; set; }
    public decimal? InsuranceRate { get; set; }
    public string InternNotUseFlag { get; set; }
    public string IpdNotPrintFlag { get; set; }
    public string IpdQtyPrintFlag { get; set; }
    public string LabelName { get; set; }
    public decimal? MaxDosePerDay { get; set; }
    public decimal? MinDosePerDay { get; set; }
    public decimal? MlSolventVolume { get; set; }
    public string NhsoFlag { get; set; }
    public string NhsoHc { get; set; }
    public decimal? NhsoIpdRate { get; set; }
    public decimal? NhsoRate { get; set; }
    public string NotDivideFlag { get; set; }
    public string NotUsePtFlag { get; set; }
    public string SsoFlag { get; set; }
    public string SsoHc { get; set; }
    public decimal? SsoIpdRate { get; set; }
    public decimal? SsoRate { get; set; }
    public string LinkQrcode { get; set; }
    public string Claimcat { get; set; }
    public string BagSpecialDrug { get; set; }
    public string DocSignFlag { get; set; }
    public string Fptype { get; set; }
    public string InnovationDrug { get; set; }
    public string SampleFlag { get; set; }
    public string Liscode { get; set; }
    public string SpecialPp { get; set; }
    public decimal? RepaceId { get; set; }
    public string DrugReportGroup { get; set; }
    public string CompanyCanceledFlag { get; set; }
    public string DrugInProjectFlag { get; set; }
    public string DrugParticularFlag { get; set; }
    public string OutOfStockFlag { get; set; }
    public string Account { get; set; }
    public string NotDiscountFlag { get; set; }
    public string DentalFlag { get; set; }
    public string DontShow { get; set; }
    public string NotTranferAbleFlag { get; set; }
    public string Anticoagulant { get; set; }
    public string ExpensiveFlag { get; set; }
    public string AcceptFlag { get; set; }
    public string IcdHighCost { get; set; }
    public string HighCost { get; set; }
    public string cscdGroupFlag { get; set; }
    public string cscdOpdGroup { get; set; }
    public string cscdIpdGroup { get; set; }
    public string ssoGroupFlag { get; set; }
    public string ssoOpdGroup { get; set; }
    public string ssoIpdGroup { get; set; }
    public string insuranceGroupFlag { get; set; }
    public string insuranceOpdGroup { get; set; }
    public string insuranceIpdGroup { get; set; }
    public string nhsoGroupFlag { get; set; }
    public string nhsoOpdGroup { get; set; }
    public string nhsoIpdGroup { get; set; }
    public string alienGroupFlag { get; set; }
    public string alienOpdGroup { get; set; }
    public string alienIpdGroup { get; set; }
    public string TransfusionReactionFlag { get; set; }
    public string AncFlag { get; set; }
    public string DiagFlag { get; set; }

    public string Lifelabflag { get; set; }
    public string Labagian { get; set; }
    public string LabagianFrequency { get; set; }
    public string LockLabagian { get; set; }
    public string DocConfirm { get; set; }
    //public string DocSpecialty { get; set; }
    public string ResidentFlag { get; set; }
    public string StaffFlag { get; set; }
    public string ExternFlag { get; set; }
    public string InternFlag { get; set; }
    public string PartTimeFlag { get; set; }
    public string NotDocTypeFlag { get; set; }
    public string LockPecialtiesFlag { get; set; }
    public string LockSpecialties { get; set; }
    public string LockSpecialtiesConsult { get; set; }
    public string LockDoctorFlag { get; set; }
    public string LockDoctor { get; set; }
    public string LockDoctorConsult { get; set; }
    public string ClinicLab { get; set; }

}